export const WORK_ORDER_STATUSES = [
  { value: 'DRAFT', label: 'Draft', color: 'bg-gray-100 text-gray-700' },
  { value: 'SUBMITTED', label: 'Submitted', color: 'bg-blue-100 text-blue-700' },
  { value: 'APPROVED', label: 'Approved', color: 'bg-green-100 text-green-700' },
  { value: 'DESIGN_ASSIGNED', label: 'Design Assigned', color: 'bg-purple-100 text-purple-700' },
  { value: 'DESIGN_IN_PROGRESS', label: 'Design In Progress', color: 'bg-indigo-100 text-indigo-700' },
  { value: 'DESIGN_COMPLETED', label: 'Design Completed', color: 'bg-teal-100 text-teal-700' },
  { value: 'DESIGN_APPROVED', label: 'Design Approved', color: 'bg-emerald-100 text-emerald-700' },
  { value: 'READY_FOR_PRODUCTION', label: 'Ready For Production', color: 'bg-cyan-100 text-cyan-700' },
  { value: 'PRODUCTION_STARTED', label: 'Production Started', color: 'bg-orange-100 text-orange-700' },
  { value: 'PRODUCTION_COMPLETED', label: 'Production Completed', color: 'bg-lime-100 text-lime-700' },
  { value: 'DELIVERED', label: 'Delivered', color: 'bg-green-100 text-green-700' },
  { value: 'CLOSED', label: 'Closed', color: 'bg-gray-100 text-gray-700' },
  { value: 'CANCELLED', label: 'Cancelled', color: 'bg-red-100 text-red-700' },
  { value: 'WORK_ORDER_CREATED', label: 'Work Order Created', color: 'bg-blue-100 text-blue-700' },
  { value: 'DESIGN_SUBMITTED', label: 'Design Submitted', color: 'bg-indigo-100 text-indigo-700' },
  { value: 'MATERIAL_REVIEW', label: 'Material Review', color: 'bg-cyan-100 text-cyan-700' },
  { value: 'IN_PRODUCTION', label: 'In Production', color: 'bg-orange-100 text-orange-700' },
  { value: 'READY_FOR_DELIVERY', label: 'Ready For Delivery', color: 'bg-emerald-100 text-emerald-700' },
] as const

export const ROLES = {
  OWNER: 'Owner',
  MANAGER: 'Main Manager',
  DESIGNER: 'Designer',
  INVENTORY_MANAGER: 'Inventory Manager',
  ACCOUNTANT: 'Accountant',
  HR: 'HR Manager',
  LABOUR: 'Worker',
  DRIVER: 'Driver',
  PRODUCTION_MANAGER: 'Production Manager',
} as const

export const INVENTORY_CATEGORIES = [
  'Wood', 'Plywood', 'MDF', 'Hardware', 'Handles',
  'Glass', 'Metal', 'Paint', 'Accessories', 'Custom Materials',
] as const

export const PRIORITIES = [
  { value: 'LOW', label: 'Low', color: 'bg-gray-100 text-gray-600' },
  { value: 'MEDIUM', label: 'Medium', color: 'bg-yellow-100 text-yellow-700' },
  { value: 'HIGH', label: 'High', color: 'bg-orange-100 text-orange-700' },
  { value: 'URGENT', label: 'Urgent', color: 'bg-red-100 text-red-700' },
] as const

export const NAV_ITEMS = {
  OWNER: [
    { label: 'Dashboard', href: '/dashboard/owner', icon: 'LayoutDashboard' },
    { label: 'Factory Ops', href: '/dashboard/factory', icon: 'Factory' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Schedule', href: '/schedule', icon: 'Calendar' },
    { label: 'Analytics', href: '/dashboard/owner/analytics', icon: 'BarChart3' },
    { label: 'Customers', href: '/customers', icon: 'Users' },
    { label: 'Employees', href: '/employees', icon: 'Users' },
    { label: 'Payroll', href: '/employees/payroll', icon: 'Wallet' },
    { label: 'Accounting', href: '/accounting', icon: 'Landmark' },
    { label: 'Inventory', href: '/inventory', icon: 'Package' },
    { label: 'Inventory Usage', href: '/dashboard/inventory-manager/usage', icon: 'BarChart3' },
    { label: 'Material Requests', href: '/material-requests', icon: 'ClipboardCheck' },
    { label: 'Purchases', href: '/purchases', icon: 'ShoppingCart' },
    { label: 'Suppliers', href: '/suppliers', icon: 'Building2' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Audit Log', href: '/audit-log', icon: 'Search' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  MANAGER: [
    { label: 'Dashboard', href: '/dashboard/manager', icon: 'LayoutDashboard' },
    { label: 'Factory Ops', href: '/dashboard/factory', icon: 'Factory' },
    { label: 'Schedule', href: '/schedule', icon: 'Calendar' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'New Work Order', href: '/work-orders/new', icon: 'PlusCircle' },
    { label: 'Designs', href: '/designs', icon: 'PenTool' },
    { label: 'Customers', href: '/customers', icon: 'Users' },
    { label: 'Inventory', href: '/inventory', icon: 'Package' },
    { label: 'Material Requests', href: '/material-requests', icon: 'ClipboardCheck' },
    { label: 'Purchases', href: '/purchases', icon: 'ShoppingCart' },
    { label: 'Suppliers', href: '/suppliers', icon: 'Building2' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  DESIGNER: [
    { label: 'Dashboard', href: '/dashboard/designer', icon: 'LayoutDashboard' },
    { label: 'My Assignments', href: '/designs', icon: 'PenTool' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  INVENTORY_MANAGER: [
    { label: 'Dashboard', href: '/dashboard/inventory-manager', icon: 'LayoutDashboard' },
    { label: 'Inventory', href: '/inventory', icon: 'Package' },
    { label: 'Inventory Usage', href: '/dashboard/inventory-manager/usage', icon: 'BarChart3' },
    { label: 'Material Analysis', href: '/dashboard/inventory-manager/analysis', icon: 'Search' },
    { label: 'Material Requests', href: '/material-requests', icon: 'ClipboardCheck' },
    { label: 'Purchases', href: '/purchases', icon: 'ShoppingCart' },
    { label: 'Suppliers', href: '/suppliers', icon: 'Building2' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  ACCOUNTANT: [
    { label: 'Dashboard', href: '/dashboard/accountant', icon: 'LayoutDashboard' },
    { label: 'Material Approvals', href: '/dashboard/accountant/material-approvals', icon: 'ClipboardCheck' },
    { label: 'Material Requests', href: '/material-requests', icon: 'Package' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Expenses', href: '/accounting/expenses', icon: 'Receipt' },
    { label: 'Payments', href: '/accounting/payments', icon: 'CreditCard' },
    { label: 'Purchases', href: '/purchases', icon: 'ShoppingCart' },
    { label: 'Accounting', href: '/accounting', icon: 'Landmark' },
    { label: 'Reports', href: '/accounting/reports', icon: 'FileText' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  HR: [
    { label: 'Dashboard', href: '/dashboard/hr', icon: 'LayoutDashboard' },
    { label: 'Employees', href: '/employees', icon: 'Users' },
    { label: 'Payroll', href: '/employees/payroll', icon: 'Wallet' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  LABOUR: [
    { label: 'Dashboard', href: '/dashboard/labour', icon: 'LayoutDashboard' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  DRIVER: [
    { label: 'Dashboard', href: '/dashboard/labour', icon: 'LayoutDashboard' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
  PRODUCTION_MANAGER: [
    { label: 'Factory Ops', href: '/dashboard/factory', icon: 'Factory' },
    { label: 'Production Board', href: '/dashboard/production', icon: 'LayoutDashboard' },
    { label: 'Schedule', href: '/schedule', icon: 'Calendar' },
    { label: 'Work Orders', href: '/work-orders', icon: 'ClipboardList' },
    { label: 'Inventory', href: '/inventory', icon: 'Package' },
    { label: 'Notifications', href: '/notifications', icon: 'Bell' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
} as const
