import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

async function main() {
  console.log("Clearing all data except Users...")

  await prisma.jobCardChecklistItem.deleteMany()
  await prisma.digitalSignature.deleteMany()
  await prisma.jobCard.deleteMany()
  await prisma.workerAssignment.deleteMany()
  await prisma.delayAlert.deleteMany()
  await prisma.installment.deleteMany()
  await prisma.laborEntry.deleteMany()
  await prisma.purchaseApproval.deleteMany()
  await prisma.materialRequest.deleteMany()
  await prisma.scheduleEvent.deleteMany()
  await prisma.productionStage.deleteMany()
  await prisma.activityHistory.deleteMany()
  await prisma.notification.deleteMany()
  await prisma.auditLog.deleteMany()
  await prisma.purchaseEntryItem.deleteMany()
  await prisma.purchaseDocument.deleteMany()
  await prisma.purchaseEntry.deleteMany()
  await prisma.designApproval.deleteMany()
  await prisma.designRevision.deleteMany()
  await prisma.design.deleteMany()
  await prisma.document.deleteMany()
  await prisma.expense.deleteMany()
  await prisma.payment.deleteMany()
  await prisma.purchaseOrder.deleteMany()
  await prisma.workOrderInventory.deleteMany()
  await prisma.inventoryMovement.deleteMany()
  await prisma.inventoryItem.deleteMany()
  await prisma.inventoryCategory.deleteMany()
  await prisma.workOrderTeamMember.deleteMany()
  await prisma.workOrderMaterial.deleteMany()
  await prisma.attendance.deleteMany()
  await prisma.payroll.deleteMany()
  await prisma.employee.deleteMany()
  await prisma.workOrder.deleteMany()
  await prisma.supplier.deleteMany()
  await prisma.customer.deleteMany()

  const userCount = await prisma.user.count()
  console.log(`Done. ${userCount} users preserved.`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
